######################## default configuration ####################
# Your theme name
theme: "dot-org-hugo-theme"
# Title of your website (required).
title: "19th SWS Europe Chapter Conference"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone: "America/Los_Angeles"

######################## i18n ####################
# Auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
hasCJKLanguage: true
# Set default content directory for multilingual
contentDir: content/en/
# Set fallback if international version is not available
defaultContentLanguage: en
# Set the default language as the root rather than in folder i.e. don't use /en/
defaultContentLanguageInSubdir: false

######################## privacy & speed ####################
# Enable do not track, no cookies on Video embeds
privacy:
  youtube:
    privacyEnhanced: true
  vimeo:
    enableDNT: true

menu:
  main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Call for abstracts
    pageRef: /register
    weight: 20
  - name: Conference
    identifier: conference
    weight: 30
  - name: Programme Overview
    pageRef: /agenda
    weight: 10
    parent: conference
  - name: Keynote Speakers
    pageRef: /speakers
    weight: 20
    parent: conference
  - name: Scientific committee
    pageRef: /scientific
    weight: 30
    parent: conference
  - name: Organising committee
    pageRef: /organising
    weight: 40
    parent: conference
  - name: Costs
    pageRef: /costs
    weight: 50
    parent: conference
  - name: Contact
    pageRef: /contact
    weight: 40
