######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/cncf/dot-org-hugo-theme"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/cloud-native-computing-foundation"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

sponsors_logos:
  a: "/images/logo/sws.png"
  b: "/images/logo/prohabitat.jpg"
  c: "/images/logo/bbpn.jpg"
  d: "/images/logo/cmok.png"
  e: "/images/logo/uw.png"
  f: "/images/logo/pb.png"
  g: "/images/logo/sggw.png"
