######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "https://swseurope2024.bagna.pl"
googleAnalytics:
enableRobotsTXT: true
build:
  writeStats: true
canonifyURLs: true
